name: expression_cli
description: A sample command-line application with basic argument parsing.
version: 0.0.1
repository: https://github.com/FilledStacks/expression-ui

environment:
  sdk: ^3.3.3

dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  path: ^1.9.0
  rive_common: 0.4.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
