name: expression_cli
description: A sample command-line application with basic argument parsing.
version: 0.0.1
repository: https://github.com/FilledStacks/expression-ui

environment:
  sdk: ^3.3.3

dependencies:
  ansicolor: ^2.0.2
  args: ^2.4.2
  collection: ^1.18.0
  expression_ui: ^0.2.0
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  json_annotation: ^4.9.0
  mustachex: ^1.0.0
  path: ^1.9.0
  recase: ^4.1.0
  rive_common: 0.4.5

dev_dependencies:
  build_runner: ^2.4.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
